import { posts } from "../src/blog-content.ts"

export const staticRoutes = [
  "/",
  "/decision-review",
  "/pricing",
  "/docs",
  "/how-we-work",
  "/docs/guides",
  "/changelog",
  "/blog",
  ...posts.map((post) => `/blog/${post.slug}`),
  "/newsroom",
  "/playground",
  "/research",
  "/about",
  "/security",
  "/media",
  "/contact",
  "/contact/sales",
  "/contact/support",
  "/contact/startup-program",
  "/legal/terms-of-service",
  "/legal/privacy-policy",
]

export const notFoundRoute = "/__not-found__"

export const redirectRoutes = [
  { from: "/velocity", to: "/" },
  { from: "/desk", to: "/" },
  { from: "/desk/signup", to: "/" },
  { from: "/dashboard", to: "/" },
  { from: "/dashboard/login", to: "/" },
  { from: "/dashboard/signup", to: "/" },
  { from: "/legal/subprocessors", to: "/security" },
  { from: "/products", to: "/decision-review" },
  { from: "/products/strategy", to: "/decision-review" },
  { from: "/products/ai-automation", to: "/decision-review" },
  { from: "/products/systems-operations", to: "/decision-review" },
  { from: "/products/solution-design", to: "/decision-review" },
  { from: "/products/implementation", to: "/decision-review" },
  { from: "/products/transformation", to: "/decision-review" },
  { from: "/products/judgement", to: "/how-we-work" },
  { from: "/features", to: "/decision-review" },
  { from: "/enterprise", to: "/decision-review" },
  { from: "/customers", to: "/decision-review" },
  { from: "/solutions/growth", to: "/decision-review" },
  { from: "/solutions/operations", to: "/decision-review" },
  { from: "/solutions/customer-experience", to: "/decision-review" },
  { from: "/solutions/technology-leaders", to: "/decision-review" },
  { from: "/solutions/regulated", to: "/decision-review" },
  { from: "/languages", to: "/decision-review" },
  { from: "/status", to: "/contact" },
  { from: "/careers", to: "/about" },
  { from: "/docs/api-reference", to: "/how-we-work#stages" },
  { from: "/method", to: "/how-we-work#stages" },
  { from: "/understand", to: "/how-we-work#understand" },
  { from: "/structure", to: "/how-we-work#structure" },
  { from: "/priorities", to: "/how-we-work#prioritize" },
]
